### PR TITLE
Update dependencies to reduce the number of warnings emitted by Elixir 1.17

### PR DESCRIPTION
**Pull request by alco**

### CODE REVIEW

**Comment by josevalim** [comment]
Streamdata no longer supports Elixir v1.6.6 but we can probably bump the Elixir requirement a bit here :D

**Comment by alco** [comment]
@josevalim The `nimble_parsec` dependency got its Elixir version requirement bumped from `1.6` to `1.12` in November 2023 - https://github.com/dashbitco/nimble_parsec/commit/be6c5ac64d32a9c9bb687cceed976a7df39947d1#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308.

I couldn't compile OTP 21 or 22 to test `makeup` with Elixir v1.6 on my machine. And when I tried to run a `hexpm/elixir:1.6-...` Docker image, I couldn't even fetch dependencies of `makeup` due to a function clause error inside Hex.

Unless there are good reasons to keep supporting such early versions of Elixir, it seems reasonable to bump the requirement here to at least Elixir v1.12.

**Comment by josevalim** [comment]
1.12spunds good to me.

**Comment by alco** [comment]
@josevalim Updated. Please take another look.

**Comment by josevalim** [comment]
I think we also have to update CI files. :)

**Comment by alco** [comment]
@josevalim right. I don't what is your policy with regards to which versions should be used on CI. Do we bump 1.6.6 to 1.12.0 or 1.12.3? Elixir 1.12.x has builds agains otp-22, otp-23 and otp-24. Should the earlier or the latest of those be used?

I'm also not sure about the purpose of testing with Elixir v1.13.3 + list. Was this job created at the time when Elixir was the latest version? Should it be bumped to 1.17.0-otp-27 then?

**Comment by josevalim** [comment]
I usually use the minimum supported Elixir version with the minimum support OTP version and the latest Elixir version with the latest OTP version. However, it should probably be 1.16.2 with OTP 26, since 1.17 is not officially out yet.

**Comment by SteffenDE** [comment]
ping @josevalim

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
