### PR TITLE
Add GitHub Action CI

### LINKED ISSUE #43: Add CI
@kianmeng, would you like to send a PR for this? :)

### PR DESCRIPTION
**Pull request by kianmeng**
This resolves https://github.com/elixir-makeup/makeup/issues/43.

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by kianmeng** [comment]
I've noticed you've [disabled](https://github.com/elixir-makeup/makeup/commit/18d38e76f8a2fdb98ccee93f74a57a6430843e3a) the `mix format` job. Should we add the `.formatter.exs` and `mix format` the whole project?

**Comment by josevalim** [comment]
I will let @tmbb do it if he wants to. otherwise we can do it later :)

**Comment by tmbb** [comment]
> I will let @tmbb do it if he wants to. otherwise we can do it later :)

I believe there was once a reason we weren't blindly running the formatter, right? Maybe something to do with the modules that are generated from Pygments? I can't recall what the reason was, and if no one can either, we could run the formatter.

**Pull request merged**
